# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ledger` gem.
# Please instead update this file by running `bin/tapioca gem ledger`.


# source://ledger//lib/ledger.rb#5
module Ledger; end

# source://ledger//lib/ledger.rb#6
class Ledger::Error < ::StandardError; end

# source://ledger//lib/ledger/version.rb#4
Ledger::VERSION = T.let(T.unsafe(nil), String)
