# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-rails` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-rails`.


# source://sorbet-rails//lib/sorbet-rails.rb#2
module SorbetRails; end
