require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.3
  NewCops: enable

Style/ClassAndModuleChildren: 
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 6

Layout/LineLength:
  Max: 130