services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgres
      MYSQL_HOST: mysql
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - mysql
      - postgres
    command: sleep infinity

  mysql:
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/postgresql/data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: ledger_test
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ledger_test

volumes:
  postgres-data:
  mysql-data:
