postgres:
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  adapter: postgresql
  encoding: unicode
  database: ledger_test
  pool: 100
  username: postgres
  password:
  min_messages: warning
mysql:
  host: <%= ENV.fetch('MYSQL_HOST') { '127.0.0.1' } %>
  adapter: mysql2
  encoding: utf8
  database: ledger_test
  pool: 100
  username: root
  password:
sqlite:
  adapter: sqlite3
  encoding: utf8
  database: tmp/ledger_test.sqlite3
  pool: 100
